post:
  title:
    max_length: 255
  box_size:
    rows: 10
    cols: 50
user:
  full_name:
    max_length: 255
  avatar:
    accept: "image/jpeg,image/gif,image/png"
    current_size: 250
    max_size: 5
    default: "avatar.jpg"
    current_user: 30
    comment_avatar: 40
    head_post: 55
  phone:
    max_length: 13
comment:
  box_size:
    col: 10
    rows: 2
  box_comment:
    cols: 50
    rows: 10
comments:
  page:
    begin: 1
  per_page: 5
posts:
  per_page: 10
